# Generated by Django 5.1 on 2024-08-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Apponitment",
            new_name="Appointment",
        ),
    ]
