# Generated by Django 5.1 on 2024-08-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0002_rename_apponitment_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="doctor_id",
        ),
    ]
